basePath: /
definitions:
  requests.SongRequest:
    description: Структура запроса для создания новой песни
    properties:
      group:
        example: Muse
        minLength: 0
        type: string
      song:
        example: Supermassive Black Hol
        minLength: 0
        type: string
    required:
    - group
    - song
    type: object
  requests.UpdateRequest:
    properties:
      group:
        example: Eminem
        minLength: 0
        type: string
      link:
        example: http://example.com
        minLength: 0
        type: string
      releaseDate:
        example: 00.00.00
        minLength: 0
        type: string
      song:
        example: SOng
        minLength: 0
        type: string
      text:
        example: LaLala
        minLength: 0
        type: string
    required:
    - group
    - link
    - releaseDate
    - song
    - text
    type: object
  responses.DeleteResponse:
    properties:
      message:
        example: Delete succeeded
        type: string
    type: object
  responses.ErrorResponse400:
    properties:
      code:
        example: 400
        type: integer
      message:
        example: Bad Request - Invalid input data
        type: string
    type: object
  responses.ErrorResponse404:
    properties:
      code:
        example: 404
        type: integer
      message:
        example: Not Found - Song not found
        type: string
    type: object
  responses.ErrorResponse422:
    properties:
      code:
        example: 422
        type: integer
      message:
        example: Unprocessable Entity - Validation failed
        type: string
    type: object
  responses.ErrorResponse500:
    properties:
      code:
        example: 500
        type: integer
      message:
        example: Internal Server Error
        type: string
    type: object
  responses.SongInfoResponse:
    description: Response structure containing song information
    properties:
      group:
        example: Muse
        type: string
      link:
        example: https://www.youtube.com/watch?v=Xsp3_a-PMTw
        minLength: 0
        type: string
      releaseDate:
        example: 16.07.2006
        minLength: 0
        type: string
      song:
        example: Supermassive Black Hol
        type: string
      text:
        example: |-
          Ooh baby, don't you know I suffer?
          Ooh baby, can you hear me moan?
          You caught me under false pretenses
          How long before you let me go?

          Ooh
          You set my soul alight
          Ooh
          You set my soul alight
        minLength: 0
        type: string
    required:
    - link
    - releaseDate
    - text
    type: object
  responses.SongResponse:
    properties:
      song:
        type: string
      verses:
        items:
          type: string
        type: array
    type: object
  responses.SongsPaginationResponse:
    properties:
      limit:
        example: 10
        type: integer
      page:
        example: 1
        type: integer
      songs:
        items:
          $ref: '#/definitions/responses.SongInfoResponse'
        type: array
      total:
        example: 31
        type: integer
      total_pages:
        example: 4
        type: integer
    type: object
  responses.UpdateResponse:
    properties:
      message:
        example: Update succeeded
        type: string
    type: object
host: localhost:3000
info:
  contact: {}
  description: Rest API Library
  termsOfService: http://swagger.io/terms/
  title: TZ
  version: "1.0"
paths:
  /song:
    post:
      consumes:
      - application/json
      description: Create a new song entry
      parameters:
      - description: Song data
        in: body
        name: song
        required: true
        schema:
          $ref: '#/definitions/requests.SongRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.SongInfoResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responses.ErrorResponse400'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/responses.ErrorResponse404'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/responses.ErrorResponse422'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responses.ErrorResponse500'
      summary: Add a new song
      tags:
      - Songs
  /song-verse:
    get:
      consumes:
      - application/json
      description: Get song with pagination on verses
      parameters:
      - description: Song filter
        in: query
        name: song
        type: string
      - description: Verses filter
        in: query
        name: verses
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.SongResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responses.ErrorResponse400'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/responses.ErrorResponse404'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responses.ErrorResponse500'
      summary: Get Songs With Verses
      tags:
      - Songs
  /song/{id}:
    delete:
      consumes:
      - application/json
      description: Delete songs
      parameters:
      - description: song id
        in: path
        name: id
        required: true
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.DeleteResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responses.ErrorResponse400'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responses.ErrorResponse500'
      summary: Delete songs
      tags:
      - Songs
    patch:
      consumes:
      - application/json
      description: Update songs
      parameters:
      - description: song id
        in: path
        name: id
        required: true
        type: string
      - description: Song data
        in: body
        name: song
        required: true
        schema:
          $ref: '#/definitions/requests.UpdateRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.UpdateResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responses.ErrorResponse400'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responses.ErrorResponse500'
      summary: Update songs
      tags:
      - Songs
  /songs:
    get:
      consumes:
      - application/json
      description: Get songs with filtr and pagination
      parameters:
      - description: Page number
        in: query
        name: page
        type: integer
      - description: Number of items per page
        in: query
        name: limit
        type: integer
      - description: Group filter
        in: query
        name: group
        type: string
      - description: Song filter
        in: query
        name: song
        type: string
      - description: releaseDate filter
        in: query
        name: releaseDate
        type: string
      - description: Text filter
        in: query
        name: text
        type: string
      - description: Link filter
        in: query
        name: link
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.SongsPaginationResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/responses.ErrorResponse404'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responses.ErrorResponse500'
      summary: Get songs
      tags:
      - Songs
swagger: "2.0"
