basePath: /
definitions:
  api.SongInfoResponse:
    description: Response structure containing song information
    properties:
      group:
        example: Beatles
        type: string
      link:
        example: https://example.com/song
        minLength: 0
        type: string
      releaseDate:
        example: "1965-08-06"
        minLength: 0
        type: string
      song:
        example: Yesterday
        type: string
      text:
        example: Yesterday, all my troubles seemed so far away...
        minLength: 0
        type: string
    required:
    - link
    - releaseDate
    - text
    type: object
  endpoints.ErrorResponse:
    description: Структура ответа при возникновении ошибки
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
  endpoints.SongRequest:
    description: Структура запроса для создания новой песни
    properties:
      group:
        example: Beatles
        minLength: 0
        type: string
      song:
        example: Yesterday
        minLength: 0
        type: string
    required:
    - group
    - song
    type: object
host: localhost:3000
info:
  contact: {}
  description: Rest API Library
  termsOfService: http://swagger.io/terms/
  title: TZ
  version: "1.0"
paths:
  /song:
    post:
      consumes:
      - application/json
      description: Create a new song entry
      parameters:
      - description: Song data
        in: body
        name: song
        required: true
        schema:
          $ref: '#/definitions/endpoints.SongRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/api.SongInfoResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/endpoints.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/endpoints.ErrorResponse'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/endpoints.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/endpoints.ErrorResponse'
      summary: Add a new song
      tags:
      - Songs
swagger: "2.0"
