basePath: /
definitions:
  requests.SongRequest:
    description: Структура запроса для создания новой песни
    properties:
      group:
        example: Muse
        minLength: 0
        type: string
      song:
        example: Supermassive Black Hol
        minLength: 0
        type: string
    required:
    - group
    - song
    type: object
  responses.ErrorResponse:
    description: Структура ответа при возникновении ошибки
    properties:
      code:
        type: integer
      message:
        type: string
    type: object
  responses.SongInfoResponse:
    description: Response structure containing song information
    properties:
      group:
        example: Muse
        type: string
      link:
        example: https://www.youtube.com/watch?v=Xsp3_a-PMTw
        minLength: 0
        type: string
      releaseDate:
        example: 16.07.2006
        minLength: 0
        type: string
      song:
        example: Supermassive Black Hol
        type: string
      text:
        example: |-
          Ooh baby, don't you know I suffer?
          Ooh baby, can you hear me moan?
          You caught me under false pretenses
          How long before you let me go?

          Ooh
          You set my soul alight
          Ooh
          You set my soul alight
        minLength: 0
        type: string
    required:
    - link
    - releaseDate
    - text
    type: object
  responses.SongsPaginationResponse:
    properties:
      limit:
        example: 10
        type: integer
      page:
        example: 1
        type: integer
      songs:
        items:
          $ref: '#/definitions/responses.SongInfoResponse'
        type: array
      total:
        example: 31
        type: integer
      total_pages:
        example: 4
        type: integer
    type: object
host: localhost:3000
info:
  contact: {}
  description: Rest API Library
  termsOfService: http://swagger.io/terms/
  title: TZ
  version: "1.0"
paths:
  /song:
    post:
      consumes:
      - application/json
      description: Create a new song entry
      parameters:
      - description: Song data
        in: body
        name: song
        required: true
        schema:
          $ref: '#/definitions/requests.SongRequest'
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.SongInfoResponse'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/responses.ErrorResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/responses.ErrorResponse'
        "422":
          description: Unprocessable Entity
          schema:
            $ref: '#/definitions/responses.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responses.ErrorResponse'
      summary: Add a new song
      tags:
      - Songs
  /songs:
    get:
      consumes:
      - application/json
      description: Get songs with filtr and pagination
      parameters:
      - description: Page number
        in: query
        name: page
        type: integer
      - description: Number of items per page
        in: query
        name: limit
        type: integer
      - description: Group filter
        in: query
        name: group
        type: string
      - description: Song filter
        in: query
        name: song
        type: string
      - description: releaseDate filter
        in: query
        name: releaseDate
        type: string
      - description: Text filter
        in: query
        name: text
        type: string
      - description: Link filter
        in: query
        name: link
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/responses.SongsPaginationResponse'
        "404":
          description: Not Found
          schema:
            $ref: '#/definitions/responses.ErrorResponse'
        "500":
          description: Internal Server Error
          schema:
            $ref: '#/definitions/responses.ErrorResponse'
      summary: Get songs
      tags:
      - Songs
swagger: "2.0"
